### PR TITLE
Update license to AGPLv3

### PR DESCRIPTION
**Pull request by ricrosales**
Propose updating license for the repository to ensure that future use of the shenanigan-scanning tools is open and attributable back to the project.

### CODE REVIEW

**Comment by nickbax** [comment]
I brought this up on Discord after I saw this tweet: https://twitter.com/LefterisJP/status/1487050478076764167
```
We have very strong suspicions a closed SaaS product has based their code on
 @rotkiapp
's code
 :Neutral face:

They have no attribution to us (or any other #opensource software) and they have no code opensource.
```

I would be very annoyed if someone used our code for closed SaaS without attribution.
I want to make sure we have a license that potentially gives some recourse if this happens. At least at a karmic level.

**Comment by Barabazs** [comment]
Let's say I use the code from this repo in a closed-source repo, but I **don't** modify the honestNFT code that I use.
Would the AGPLv3 restrictions/obligations apply to me?

**Comment by ricrosales** [comment]
@Barabazs - My understanding is that in the scenario you describe, you would have to make the code public if and only if you are distributing the code in any way. For example, if you have a server running a modified version of the code and this server has a public api, then you would be compelled to make the code public and share your changes. However, if you are using the modified code on a private server (even if for commercial use), I don't think you are compelled to make the code/changes public.

**Comment by ricrosales** [comment]
Here is a good description of the license from Fossa: https://fossa.com/blog/open-source-software-licenses-101-agpl-license/

**Comment by ricrosales** [comment]
We're going to stay on MIT for the time being.

**Pull request closed without merging**
